version: '2'

services:
  nginx:
    container_name: nginx-evertec-test-sf
    image: nginx:latest
    ports:
      - "8086:80"
    links:
      - php
    volumes:
      - ./build/nginx/evertec-test.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    networks:
      symfony:
        aliases:
          - webserver-sf
  php:
    container_name: php7-evertec-test-sf
    build: './'
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@mysql:3306/evertec?serverVersion=5.7
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1
    expose:
      - "9000"
    volumes:
      - ./symfony:/var/www/symfony/
    networks:
      symfony:
        aliases:
          - php-sf
    depends_on:
        - mysql  
  mysql:
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    container_name: mysql-evertec-test-sf
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./build/mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      MYSQL_DATABASE: evertec
      MYSQL_PASSWORD: 3v3rt3cT3st      
    networks:
      symfony:
        aliases:
          - dbserver-sf        
  phpmyadmin:
    container_name: phpmyadmin-evertec-test-sf
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8096:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 3v3rt3cT3st  
    networks:
      symfony:
        aliases:
          - phpmyadmin-dbserver-sf            
networks:
    symfony: